name: Test on Pull Request to Main

on:
  pull_request:
    branches:
      - main

jobs:
  test-unit-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          architecture: x64
          cache: maven
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

  test-unit-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.24.4"
          go-version-file: ./instrumentation/go.mod
      - name: Run Go tests
        run: go test ./...
        working-directory: ./instrumentation

  integration-test:
    runs-on: ubuntu-latest
    needs:
      - test-unit-java
      - test-unit-go
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          architecture: x64
          cache: maven
      - name: Build all
        run: make build-all
      - name: Run integration test
        run: mvn test -Dtest=MetaSuiteIT#testRegister+testGlobalFaultload
